mysite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('<int:pk>', views.FoodDetail.as_view(), name="detail"),
    path('', views.IndexClassView.as_view(), name="index"),
    path('item/', views.item, name="item"),
    path('add', views.CreateItem.as_view(), name="create_item"),
    path('update/<int:id>', views.update_item, name="update_item"),
    path('delete/<int:id>', views.delete_item, name="delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('challenge/', include('Challenge.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('profile/', user_views.profilepage, name="profile")
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):

    def __str__(self):
            return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://th.bing.com/th/id/OIP.Ygxe4M39-El0f3HPLQOmWQHaHa?w=191&h=191&c=7&r=0&o=7&pid=1.7&rm=3")

    def get_absolute_url(self):
          return reverse("food:detail", kwargs={"pk": self.pk})

mysite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)

# Class Based View
class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def item(request):
    return HttpResponse('This is an item view')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item' : item
    }
    return render(request, 'food/detail.html', context)
# Class based view
class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if(form.is_valid()):
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form})

class CreateItem(CreateView):
    model = Item
    fields =['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form, 'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Food App</a>
    <div class="navbar">
        <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
        <a href="#" class="nav-item nav-link">Delete Item</a>
        <a href="#" class="nav-item nav-link">View Item</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
        {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
        {% endif %}
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block body %}
{% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html'%}

{%  block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card" height="300px" src="{{ item.item_image }}"/>
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>${{item.item_price}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% block body %}
{% for item in item_list %}
    <div class="row">
        <div class="cold-md-3 offset-md-2">
            <img class="card" height="150px" src="{{ item.item_image }}"/>
        </div>
        <div class="cold-md-4">
            <h3>{{ item.item_name}}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>${{ item.item_price }}</h6>
            <h6>{{ item.user_name }}</h6>
        </div>
        <div class="cold-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-primary">Edit</a>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn-info">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}